/* globals console */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, URL } from "node:url";

const MAX_TIDE_DAYS = 14;

// Get the directory of the current file for relative path resolution
const __dirname = path.dirname(fileURLToPath(import.meta.url));

function parseTideRequest(request) {
  // Parse but don't validate the latitude/longitude since we're serving static data
  // The frontend still sends these parameters, but we ignore them
  const requestUrl = new URL(request.url, "https://fish-on.invalid");
  const days = Number(requestUrl.searchParams.get("days") ?? MAX_TIDE_DAYS);

  if (!Number.isInteger(days) || days < 1 || days > MAX_TIDE_DAYS) {
    return null;
  }

  return { days };
}

export default async function handler(request, response) {
  if (request.method !== "GET") {
    response.setHeader("Allow", "GET");
    response.status(405).json({ error: "Method not allowed" });
    return;
  }

  const tideRequest = parseTideRequest(request);
  if (!tideRequest) {
    response.status(400).json({ error: "Invalid tide request parameters" });
    return;
  }

  try {
    // Load static tide data generated by buildTides.js
    const tideDataPath = path.join(__dirname, "..", "src", "data", "tides.json");
    const staticData = JSON.parse(fs.readFileSync(tideDataPath, "utf-8"));

    if (!Array.isArray(staticData?.records)) {
      response.status(500).json({ error: "Tide data is malformed" });
      return;
    }

    // Convert static records to the extremes format expected by the frontend
    // Static records: { dt, date, height, type }
    // Extremes format: { date, height, type }
    const extremes = staticData.records.map((record) => ({
      date: record.date,
      height: record.height,
      type: record.type,
    }));

    // Limit to requested number of days
    const limitedExtremes = extremes.slice(0, tideRequest.days * 2);

    response.setHeader("Content-Type", "application/json");
    response.setHeader(
      "Cache-Control",
      "public, s-maxage=86400, stale-while-revalidate=604800",
    );
    response.status(200).json({ extremes: limitedExtremes });
  } catch (error) {
    console.error("Failed to load tide data:", error);
    response.status(500).json({ error: "Unable to retrieve tide data" });
  }
}